name: Daily Backup to GitHub
on:
"  schedule:"
"    - cron: '0 5 * * *'"
"  workflow_dispatch:"
jobs:
"  backup:"
"    runs-on: ubuntu-latest"
"    steps:"
"      - name: Checkout repo"
"        uses: actions/checkout@v3"
"      - name: Commit daily backup"
"        run: |"
"          git config user.name 'github-actions'"
"          git config user.email 'actions@github.com'"
"          git add ."
"          git commit -m 'Daily backup' || echo 'No changes to commit'"
"          git push"
