name: backup
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Prepare backup artifacts
        run: |
          mkdir -p .backup
          date -u +"%Y-%m-%dT%H:%M:%SZ" > .backup/timestamp.txt

      - name: Commit changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "chore(backup): automated backup [skip ci]"
          fi

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
