name: Deploy (Hosting + Functions)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # ---- Root (Vite) ----
      - name: Install root deps
        run: npm ci

      - name: Build web
        run: npm run build

      # ---- Functions (TypeScript) ----
      - name: Install functions deps
        working-directory: functions
        run: npm ci

      - name: Typecheck / build functions
        working-directory: functions
        run: |
          npm run typecheck --if-present
          npm run build --if-present

      # ---- Auth to Google with a Service Account JSON secret ----
      - name: Google auth (service account)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SNAGGLE_ED88D }}

      # ---- Deploy via Firebase CLI ----
      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy Hosting + Functions
        run: firebase deploy --only hosting,functions --project snaggle-ed88d