name: Build • Preview • Deploy (Firebase Hosting)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  NODE_VERSION: "20"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install deps
        run: npm ci || npm install

      - name: Lint
        run: npm run lint --if-present

      - name: Build (Vite -> dist)
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy to Firebase Hosting
        run: |
          npx firebase-tools --version
          npx firebase-tools hosting:deploy \
            --project "${{ secrets.FIREBASE_PROJECT_ID }}" \
            --site snaggle-ed88d \
            --non-interactive \
            --token "${{ secrets.FIREBASE_TOKEN }}"
