name: Build • Preview • Deploy (Firebase Hosting)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: deploy-main
  cancel-in-progress: true

env:
  NODE_VERSION: '20'
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install deps
        run: npm ci || npm install
      - name: Lint
        run: npm run lint --if-present
      - name: Build (Vite → dist)
        run: npm run build
      - name: Verify dist exists
        run: test -d dist && test "$(ls -A dist)"
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error

  deploy-preview:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Auth with service account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      - name: Install Firebase CLI
        run: npm i -g firebase-tools
      - name: Deploy to preview channel
        id: preview
        run: |
          CHANNEL="ci-${{ github.run_id }}"
          firebase hosting:channel:deploy "$CHANNEL" \
            --project "$FIREBASE_PROJECT_ID" \
            --expires 7d \
            --json > preview.json
          node -e "console.log('::notice::Preview URL: ' + require('./preview.json').result[0].url)"

  promote:
    needs: deploy-preview
    runs-on: ubuntu-latest
    steps:
      - name: Auth with service account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      - name: Install Firebase CLI
        run: npm i -g firebase-tools
      - name: Deploy to LIVE (snaggle-fun)
        run: |
          # If you have multiple hosting sites, replace 'hosting'
          # with "hosting:snaggle-fun" or your exact site ID.
          firebase deploy \
            --only "hosting" \
            --project "$FIREBASE_PROJECT_ID"
