name: Build • Preview • Deploy (Firebase Hosting)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install deps
        run: npm ci || npm install

      - name: Lint
        run: npm run lint --if-present

      - name: Build (Vite -> dist)
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error

  deploy-preview:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Firebase auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy to preview channel
        id: preview
        run: |
          CHANNEL="ci-${{ github.run_id }}"
          firebase hosting:channel:deploy "$CHANNEL" --project "${{ secrets.FIREBASE_PROJECT_ID }}" --json > preview.json
          node -e "console.log('::notice::Preview URL: ' + require('./preview.json').result[0].url)"

  promote:
    needs: deploy-preview
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      - run: npm i -g firebase-tools
      - name: Deploy to live
        run: firebase deploy --only hosting --project "${{ secrets.FIREBASE_PROJECT_ID }}"
