name: Deploy (Hosting + Functions)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install root deps
        run: npm ci

      - name: Build web
        run: npm run build

      - name: Install functions deps
        working-directory: functions
        run: npm ci

      - name: Typecheck / build functions (no-op if scripts missing)
        working-directory: functions
        run: |
          npm run typecheck --if-present
          npm run build --if-present

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13
        with:
          args: deploy --only hosting,functions --project snaggle-ed88d
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SNAGGLE_ED88D }}