name: Deploy (Hosting + Functions)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # ---- Root (Vite) ----
      - name: Install root deps
        run: npm install --no-audit --no-fund --legacy-peer-deps

      - name: Build web
        run: npm run build

      # ---- Functions (TypeScript) ----
      - name: Install functions deps
        working-directory: functions
        run: npm install --no-audit --no-fund --legacy-peer-deps

      - name: Typecheck / build functions
        working-directory: functions
        run: |
          npm run typecheck --if-present
          npm run build --if-present

      # ---- Deploy via Firebase CLI using FIREBASE_TOKEN ----
      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy Hosting + Functions
        run: firebase deploy --only hosting,functions --project snaggle-ed88d
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}