name: Verify Config

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  HOSTING_SITE: ${{ secrets.HOSTING_SITE }}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm i -g firebase-tools@latest

      - name: Authenticate to Google (service account)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Verify Firebase Project and Hosting Site
        run: |
          echo "Firebase version: $(firebase --version)"
          echo "Project (secret): $FIREBASE_PROJECT_ID"
          firebase projects:list --json | jq -r '.results[].projectId' | grep -w "$FIREBASE_PROJECT_ID"
          SITE="${HOSTING_SITE:-snaggle-fun}"
          echo "Hosting site (secret/default): $SITE"
          firebase hosting:sites:list --project "$FIREBASE_PROJECT_ID" --json | jq -r '.result[].name' | grep -w "$SITE"
          echo "✅ Verification complete: project and hosting site match secrets"
